export * as trendings from './rest/trendings'
export * as repos from './rest/repos'
export * as auth from './rest/auth'
export * as issues from './rest/issues'
export * as starred from './rest/starred'
export * as helpers from './helpers'
